import { Injectable } from '@angular/core';
import {
  BindingTypeCaseBound,
  BindingTypeFolding,
  BindingTypePaperBack,
  BindingTypeSpiralBound,
  BindingTypeStichType,
  BindingTypeWireoBinding,
  ProductSpecStoreVM,
} from '../../models/product-spec';

@Injectable({
  providedIn: 'root',
})
export class ProductSpecHelperService {
  constructor() { }

  getCaseBoundTypeObject = (): BindingTypeCaseBound => {
    return {
      bindingMethod: '',
      bookSpineType: '',
      isHeadTailBand: false,
      headTailBandColour: '',
      isRibbon: false,
      greyboardThickness: '',
      specialInstruction1: '',
      benchworkRequired: [],
      specialInstruction2: '',
      endPaperWeight: '',
      endPaperMaterial: '',
      materialBrand: '',
      noOfColourExtent: 0,
      noOfMonoExtent: 0,
      totalExtent: 0,
      noOfColours: 0,
      colorType: [],
      pantoneColour: [],
      finishingType: [],
      specialInstructions3: '',
    };
  }

  getFoldingTypeObject = (): BindingTypeFolding => {
    return {
      specialInstructions1: '',
      benchworkRequired: [],
      specialInstructions2: '',
    };
  }

  getSaddleStitchTypeObject = (): BindingTypeStichType => {
    return {
      stichType: '',
      specialInstructions1: '',
      benchworkRequired: [],
      specialInstructions2: '',
    };
  }

  getWireOBindingTypeObject = (): BindingTypeWireoBinding => {
    return {
      wireColour: '',
      specialInstructions1: '',
      benchworkRequired: [],
      specialInstructions2: '',
    };
  }

  getSpiralBoundTypeObject = (): BindingTypeSpiralBound => {
    return {
      coilColour: '',
      specialInstructions1: '',
      benchworkRequired: [],
      specialInstructions2: '',
    };
  }

  getPaperBackTypeObject = (): BindingTypePaperBack => {
    return {
      bindingMethod: '',
      specialInstructions1: '',
      benchworkRequired: [],
      specialInstructions2: '',
    };
  }

  public transCreateProductApiModal = (data: ProductSpecStoreVM) => {
    return {
      height: data.generalVM.height,
      isbn: data.productSpecVM.isbn,
      isbnOwner: data.generalVM.isbnOwner,
      printType: data.productSpecVM.printingType,
      productGroup: '',
      txtNoOfColourExtent: data.textVM.noOfColourExtent,
      txtNoOfMonoExtent: data.textVM.noOfMonoExtent,
      txtTotalExtent: data.textVM.totalExtent,
      width: data.generalVM.width,
      productDescription: data.generalVM.productDescription,
      versionNo: data.productSpecVM.version,
      activeVersion: true,
      statusCode: 0,
      versionDescription: '',
      externalPartNo: data.generalVM.externalPartNo,
      orientation: data.generalVM.orientationType,
      weight: data.generalVM.weight,
      anyChildISBN: data.generalVM.isChildIsbnAdded,
      anyCD: data.generalVM.isDvdAdded,
      anyWebCode: data.generalVM.isWebcodeAdded,
      cvrMaterialWeight: data.coverVM.coverMaterialWeight,
      cvrMaterial: data.coverVM.coverMaterial,
      cvrBrand: data.coverVM.materialBrand,
      cvrOutsideNoOfColours: data.coverVM.colorTypeOutside,
      cvrOutsideSelectedColours: '',
      cvrOutsidePantoneColours: data.coverVM.pantoneColourOutside,
      cvrOutsidePantoneColoursNo: '',
      cvrOutsideFinishing: data.coverVM.finishingTypeOutside,
      cvrInsideNoOfColours: 0,
      cvrInsideSelectedColours: '',
      cvrInsidePantoneColours: data.coverVM.pantoneColourInside,
      cvrInsidePantoneColoursNo: '',
      cvrInsideFinishing: data.coverVM.finishingTypeInside,
      cvrSpecialInstruction: data.coverVM.specialInstructions,
      txtMaterialWeight: data.textVM.textMaterialWeight,
      txtMaterial: data.textVM.textMaterial,
      txtMaterialBrand: data.textVM.materialBrand,
      txtNoOfColours: data.textVM.noOfColours,
      txtSelectedColours: '',
      txtPantoneColours: true,
      txtPantoneColoursNo: data.textVM.pantoneColour,
      txtFinishing: data.textVM.finishingType,
      slipCaseNoOfColours: 0,
      slipCaseSelectedColours: '',
      slipCasePantoneColours: data.childIsbnVM.isSlipCase,
      slipCasePantoneColoursNo: '',
      slipCaseFinishing: '',
      txtSpecialInstruction: data.textVM.specialInstructions,
      bindingType: data.bindingVM.bindingType,
      bindingStitchType: data.bindingVM.saddleStich.stichType,
      bindingMethod: data.bindingVM.caseBound.bindingMethod,
      bindingBookSpineType: data.bindingVM.caseBound.bookSpineType,
      bindingHeadTailBand: data.bindingVM.caseBound.isHeadTailBand,
      bindingHeadTailBandColour: data.bindingVM.caseBound.headTailBandColour,
      bindingGreyBoardThickness: data.bindingVM.caseBound.greyboardThickness,
      bindingMethodPerfect: '',
      bindingMethodComb: '',
      bindingMethodCoil: '',
      bindingMethodWire: '',
      bindingTypeSpecialInstruction: '',
      bindingBenchworkRequired: data.bindingVM.caseBound.benchworkRequired,
      bindingBenchworkSpecialInstruction: '',
      volSetShrinkWrapTogether: true,
      volSetShrinkSpecialInstruction: '',
      volSetSlipcase: true,
      volSetSlipCaseMaterialWeight: '',
      volSetSlipCaseMaterial: '',
      volSetSlipCaseMaterialBrand: '',
      volSetGreyboardThickness: '',
      volSetSpecialInstruction: '',
      otherSpecialInstruction: '',
      endpaperMaterialWeight: data.bindingVM.caseBound.endPaperWeight,
      endpaperMaterial: data.bindingVM.caseBound.endPaperMaterial,
      endpaperMaterialBrand: data.bindingVM.caseBound.materialBrand,
      endpaperNoOfColourExtent: data.bindingVM.caseBound.noOfColourExtent,
      endpaperNoOfMonoExtent: data.bindingVM.caseBound.noOfMonoExtent,
      endpaperTotalExtent: data.bindingVM.caseBound.totalExtent,
      endpaperNoOfColours: data.bindingVM.caseBound.noOfColours,
      endpaperSelectedColours: data.bindingVM.caseBound.pantoneColour,
      endpaperPantoneColours: true,
      endpaperPantoneColourNo: '',
      endpaperFinishing: data.bindingVM.caseBound.finishingType,
      endpaperSpecialInstruction: data.bindingVM.caseBound.specialInstructions3,
      endpaperComponentPrintingDesc: '',
      coverType: '',
      bindingRibbonColour: '',
      bindingRibbon: data.bindingVM.caseBound.isRibbon,
      spineWidth: data.generalVM.spinWidth,
      journalTitleCode: data.generalVM.journalTitleCode,
      journalVolume: data.generalVM.volume,
      journalIssue: data.generalVM.issue,
      fsc: data.generalVM.fscType,
      additionalComponentsList: [
        {
          width: data.otherVM.width,
          height: data.otherVM.height,
          orientation: data.otherVM.orientationType,
          openSize: data.otherVM.isOpenSize,
          openSizeHeight: data.otherVM.openSizeHeight,
          openSizeWidth: data.otherVM.openSizeWidth,
          materialWeight: data.otherVM.textMaterialWeight,
          material: data.otherVM.material,
          materialBrand: data.otherVM.materialBrand,
          noOfColourExtent: data.otherVM.noOfColourExtent,
          noOfMonoExtent: data.otherVM.noOfMonoExtent,
          totalExtent: data.otherVM.totalExtent,
          txtFrontNoOfColours: 0,
          txtFrontSelectedColours: '',
          txtFrontPantoneColours: true,
          txtFrontPantoneColourNo: '',
          txtFrontFinishing: '',
          txtBackNoOfColours: 0,
          txtBackSelectedColours: '',
          txtBackPantoneColours: true,
          txtBackPantoneColourNo: '',
          txtBackFinishing: '',
          bindingType: '',
          bindingStitchType: '',
          bindingMethod: '',
          bindingBookSpineType: '',
          bindingHeadTailBand: true,
          bindingHeadTailBandColour: '',
          bindingGreyBoardThickness: '',
          bindingMethodPerfect: '',
          bindingMethodComb: '',
          bindingMethodCoil: '',
          bindingMethodWire: '',
          bindingRibbon: true,
          bindingRibbonColour: '',
          bindingTypeSpecialInstruction: '',
          bindingBenchworkRequired: '',
          bindingBenchworkSpecialInstruction: '',
          endpaperMaterialWeight: '',
          endpaperMaterial: '',
          endpaperMaterialBrand: '',
          endpaperNoOfColourExtent: 0,
          endpaperNoOfMonoExtent: 0,
          endpaperTotalExtent: 0,
          endpaperNoOfColours: 0,
          endpaperSelectedColours: '',
          endpaperPantoneColours: true,
          endpaperPantoneColourNo: '',
          endpaperFinishing: '',
          endpaperSpecialInstruction: '',
          endpaperComponentPrintingDesc: '',
          specialInstruction: '',
          type: ''
        },
        {
          width: '',
          height: '',
          orientation: '',
          openSize: true,
          openSizeHeight: '0.00',
          openSizeWidth: '0.00',
          materialWeight: '',
          material: '',
          materialBrand: '',
          noOfColourExtent: 0,
          noOfMonoExtent: 0,
          totalExtent: 0,
          txtFrontNoOfColours: 0,
          txtFrontSelectedColours: '',
          txtFrontPantoneColours: true,
          txtFrontPantoneColourNo: '',
          txtFrontFinishing: '',
          txtBackNoOfColours: 0,
          txtBackSelectedColours: '',
          txtBackPantoneColours: true,
          txtBackPantoneColourNo: '',
          txtBackFinishing: '',
          bindingType: '',
          bindingStitchType: '',
          bindingMethod: '',
          bindingBookSpineType: '',
          bindingHeadTailBand: true,
          bindingHeadTailBandColour: '',
          bindingGreyBoardThickness: '',
          bindingMethodPerfect: '',
          bindingMethodComb: '',
          bindingMethodCoil: '',
          bindingMethodWire: '',
          bindingRibbon: true,
          bindingRibbonColour: '',
          bindingTypeSpecialInstruction: '',
          bindingBenchworkRequired: '',
          bindingBenchworkSpecialInstruction: '',
          endpaperMaterialWeight: '',
          endpaperMaterial: '',
          endpaperMaterialBrand: '',
          endpaperNoOfColourExtent: 0,
          endpaperNoOfMonoExtent: 0,
          endpaperTotalExtent: 0,
          endpaperNoOfColours: 0,
          endpaperSelectedColours: '',
          endpaperPantoneColours: true,
          endpaperPantoneColourNo: '',
          endpaperFinishing: '',
          endpaperSpecialInstruction: '',
          endpaperComponentPrintingDesc: '',
          specialInstruction: '',
          type: ''
        }
      ],
      cdList: [
        {
          typeOfCD: '',
          sleeveType: '',
          quantity: 0,
          frontLay: true,
          backLay: true,
          dvdInlay: true,
          cdBooklet: true,
          cdComponents: [
            {
              materialWeight: '',
              material: '',
              materialBrand: '',
              noOfColourExtent: 0,
              noOfMonoExtent: 0,
              totalExtent: 0,
              noOfColours: '',
              selectedColours: '',
              pantoneColours: true,
              pantoneColoursNo: '',
              finishing: '',
              type: '',
              width: '',
              height: '',
              orientation: '',
              openSize: true,
              openSizeHeight: '0.00',
              openSizeWidth: '0.00',
              bindingType: '',
              bindingStitchType: '',
              bindingMethod: '',
              bindingBookSpineType: '',
              bindingHeadTailBand: true,
              bindingHeadTailBandColour: '',
              bindingGreyBoardThickness: '',
              bindingMethodPerfect: '',
              bindingMethodComb: '',
              bindingMethodCoil: '',
              bindingMethodWire: '',
              bindingRibbon: true,
              bindingRibbonColour: '',
              bindingTypeSpecialInstruction: '',
              bindingBenchworkRequired: '',
              bindingBenchworkSpecialInstruction: '',
              endpaperMaterialWeight: '',
              endpaperMaterial: '',
              endpaperMaterialBrand: '',
              endpaperNoOfColourExtent: 0,
              endpaperNoOfMonoExtent: 0,
              endpaperTotalExtent: 0,
              endpaperNoOfColours: 0,
              endpaperSelectedColours: '',
              endpaperPantoneColours: true,
              endpaperPantoneColourNo: '',
              endpaperFinishing: '',
              endpaperSpecialInstruction: '',
              endpaperComponentPrintingDesc: '',
              specialInstruction: ''
            },
            {
              materialWeight: '',
              material: '',
              materialBrand: '',
              noOfColourExtent: 0,
              noOfMonoExtent: 0,
              totalExtent: 0,
              noOfColours: '',
              selectedColours: '',
              pantoneColours: true,
              pantoneColoursNo: '',
              finishing: '',
              type: '',
              width: '',
              height: '',
              orientation: '',
              openSize: true,
              openSizeHeight: '0.00',
              openSizeWidth: '0.00',
              bindingType: '',
              bindingStitchType: '',
              bindingMethod: '',
              bindingBookSpineType: '',
              bindingHeadTailBand: true,
              bindingHeadTailBandColour: '',
              bindingGreyBoardThickness: '',
              bindingMethodPerfect: '',
              bindingMethodComb: '',
              bindingMethodCoil: '',
              bindingMethodWire: '',
              bindingRibbon: true,
              bindingRibbonColour: '',
              bindingTypeSpecialInstruction: '',
              bindingBenchworkRequired: '',
              bindingBenchworkSpecialInstruction: '',
              endpaperMaterialWeight: '',
              endpaperMaterial: '',
              endpaperMaterialBrand: '',
              endpaperNoOfColourExtent: 0,
              endpaperNoOfMonoExtent: 0,
              endpaperTotalExtent: 0,
              endpaperNoOfColours: 0,
              endpaperSelectedColours: '',
              endpaperPantoneColours: true,
              endpaperPantoneColourNo: '',
              endpaperFinishing: '',
              endpaperSpecialInstruction: '',
              endpaperComponentPrintingDesc: '',
              specialInstruction: ''
            }
          ],
          isDeleted: true
        },
        {
          typeOfCD: '',
          sleeveType: '',
          quantity: 0,
          frontLay: true,
          backLay: true,
          dvdInlay: true,
          cdBooklet: true,
          cdComponents: [
            {
              materialWeight: '',
              material: '',
              materialBrand: '',
              noOfColourExtent: 0,
              noOfMonoExtent: 0,
              totalExtent: 0,
              noOfColours: '',
              selectedColours: '',
              pantoneColours: true,
              pantoneColoursNo: '',
              finishing: '',
              type: '',
              width: '',
              height: '',
              orientation: '',
              openSize: true,
              openSizeHeight: '0.00',
              openSizeWidth: '0.00',
              bindingType: '',
              bindingStitchType: '',
              bindingMethod: '',
              bindingBookSpineType: '',
              bindingHeadTailBand: true,
              bindingHeadTailBandColour: '',
              bindingGreyBoardThickness: '',
              bindingMethodPerfect: '',
              bindingMethodComb: '',
              bindingMethodCoil: '',
              bindingMethodWire: '',
              bindingRibbon: true,
              bindingRibbonColour: '',
              bindingTypeSpecialInstruction: '',
              bindingBenchworkRequired: '',
              bindingBenchworkSpecialInstruction: '',
              endpaperMaterialWeight: '',
              endpaperMaterial: '',
              endpaperMaterialBrand: '',
              endpaperNoOfColourExtent: 0,
              endpaperNoOfMonoExtent: 0,
              endpaperTotalExtent: 0,
              endpaperNoOfColours: 0,
              endpaperSelectedColours: '',
              endpaperPantoneColours: true,
              endpaperPantoneColourNo: '',
              endpaperFinishing: '',
              endpaperSpecialInstruction: '',
              endpaperComponentPrintingDesc: '',
              specialInstruction: ''
            },
            {
              materialWeight: '',
              material: '',
              materialBrand: '',
              noOfColourExtent: 0,
              noOfMonoExtent: 0,
              totalExtent: 0,
              noOfColours: '',
              selectedColours: '',
              pantoneColours: true,
              pantoneColoursNo: '',
              finishing: '',
              type: '',
              width: '',
              height: '',
              orientation: '',
              openSize: true,
              openSizeHeight: '0.00',
              openSizeWidth: '0.00',
              bindingType: '',
              bindingStitchType: '',
              bindingMethod: '',
              bindingBookSpineType: '',
              bindingHeadTailBand: true,
              bindingHeadTailBandColour: '',
              bindingGreyBoardThickness: '',
              bindingMethodPerfect: '',
              bindingMethodComb: '',
              bindingMethodCoil: '',
              bindingMethodWire: '',
              bindingRibbon: true,
              bindingRibbonColour: '',
              bindingTypeSpecialInstruction: '',
              bindingBenchworkRequired: '',
              bindingBenchworkSpecialInstruction: '',
              endpaperMaterialWeight: '',
              endpaperMaterial: '',
              endpaperMaterialBrand: '',
              endpaperNoOfColourExtent: 0,
              endpaperNoOfMonoExtent: 0,
              endpaperTotalExtent: 0,
              endpaperNoOfColours: 0,
              endpaperSelectedColours: '',
              endpaperPantoneColours: true,
              endpaperPantoneColourNo: '',
              endpaperFinishing: '',
              endpaperSpecialInstruction: '',
              endpaperComponentPrintingDesc: '',
              specialInstruction: ''
            }
          ],
          isDeleted: true
        }
      ],
      webCodeList: [
        {
          xcoordinate: '0.00',
          ycoordinate: '0.00',
          location: '',
          noOfWebcode: 0,
          specialInstruction: '',
          isDeleted: true
        },
        {
          xcoordinate: '0.00',
          ycoordinate: '0.00',
          location: '',
          noOfWebcode: 0,
          specialInstruction: '',
          isDeleted: true
        }
      ],
      volumeSetList: [
        {
          childISBNVersionNo: '',
          isbn: '',
          isDeleted: true
        },
        {
          childISBNVersionNo: '',
          isbn: '',
          isDeleted: true
        }
      ],
      actionUser: '',
      estimatedPrice: '0.00',
      openSize: true,
      openSizeHeight: '0.00',
      openSizeWidth: '0.00',
      printQuality: '',
      priceMethod: '',
      price: '0.00'
    }
  };
}
