export const BindingType = {
    CASEBOUND: 'CASEBOUND',
    FLEXIBOUND: 'FLEXIBOUND',
    FOLDING: 'FOLDING',
    FULLCANADIANWIROO: 'FULLCANADIANWIROO',
    HALFCANADIANWIROO: 'HALFCANADIANWIROO',
    PAPERBACK: 'PAPERBACK',
    SADDLESTITCH: 'SADDLESTITCH',
    SPIRALBOUND: 'SPIRALBOUND',
    TRIMTOSIZE: 'TRIMTOSIZE',
    WIREOBINDING: 'WIREOBINDING'
}