export const ProductSpecLayoutPrepProdActivityList = [
    {
        comId: 1,
        dept: 'Prepress',
        type: 'Cover',
        qty: '1',
        layout: '1pp',
        processCode: 'OP005',
        activity: 'Plates (5 Color Press)',
        units: '1',
        duration: '-',
        unitCosts: '$16',
        newUnitsCosts: '-',
        totalEstCosts: '$612',
        percentage: '2.86%'
    }, {
        comId: 1,
        dept: 'Prepress',
        type: 'Cover',
        qty: '1',
        layout: '1pp',
        processCode: 'OP005',
        activity: 'Plates (5 Color Press)',
        units: '1',
        duration: '-',
        unitCosts: '$16',
        newUnitsCosts: '-',
        totalEstCosts: '$612',
        percentage: '2.86%'
    }, {
        comId: 1,
        dept: 'Prepress',
        type: 'Cover',
        qty: '1',
        layout: '1pp',
        processCode: 'OP005',
        activity: 'Plates (5 Color Press)',
        units: '1',
        duration: '-',
        unitCosts: '$16',
        newUnitsCosts: '-',
        totalEstCosts: '$612',
        percentage: '2.86%'
    }, {
        comId: 1,
        dept: 'Prepress',
        type: 'Cover',
        qty: '1',
        layout: '1pp',
        processCode: 'OP005',
        activity: 'Plates (5 Color Press)',
        units: '1',
        duration: '-',
        unitCosts: '$16',
        newUnitsCosts: '-',
        totalEstCosts: '$612',
        percentage: '2.86%'
    }, {
        comId: 1,
        dept: 'Prepress',
        type: 'Cover',
        qty: '1',
        layout: '1pp',
        processCode: 'OP005',
        activity: 'Plates (5 Color Press)',
        units: '1',
        duration: '-',
        unitCosts: '$16',
        newUnitsCosts: '-',
        totalEstCosts: '$612',
        percentage: '2.86%'
    }, {
        comId: 1,
        dept: 'Prepress',
        type: 'Cover',
        qty: '1',
        layout: '1pp',
        processCode: 'OP005',
        activity: 'Plates (5 Color Press)',
        units: '1',
        duration: '-',
        unitCosts: '$16',
        newUnitsCosts: '-',
        totalEstCosts: '$612',
        percentage: '2.86%'
    }, {
        comId: 1,
        dept: 'Prepress',
        type: 'Cover',
        qty: '1',
        layout: '1pp',
        processCode: 'OP005',
        activity: 'Plates (5 Color Press)',
        units: '1',
        duration: '-',
        unitCosts: '$16',
        newUnitsCosts: '-',
        totalEstCosts: '$612',
        percentage: '2.86%'
    }, {
        comId: 1,
        dept: 'Prepress',
        type: 'Cover',
        qty: '1',
        layout: '1pp',
        processCode: 'OP005',
        activity: 'Plates (5 Color Press)',
        units: '1',
        duration: '-',
        unitCosts: '$16',
        newUnitsCosts: '-',
        totalEstCosts: '$612',
        percentage: '2.86%'
    },
];