export const ProductSpecLayoutPrepCompBreakList = [
    {
        id: 1,
        type: 'Cover',
        component: '1pp',
        qty: '1',
        printingSheets: '10',
        scrap: '70',
        totalSheets: '80',
        colour: '5x0',
        paper: '130gsm Glossy Artpaper',
        paperSize: '',
        machineType: '5 Color Press',
    },
    {
        id: 2,
        type: 'Text',
        component: '1pp',
        qty: '1',
        printingSheets: '10',
        scrap: '70',
        totalSheets: '80',
        colour: '5x0',
        paper: '130gsm Glossy Artpaper',
        paperSize: '',
        machineType: '5 Color Press',
    },
    {
        id: 3,
        type: 'Text',
        component: '1pp',
        qty: '1',
        printingSheets: '10',
        scrap: '70',
        totalSheets: '80',
        colour: '5x0',
        paper: '130gsm Glossy Artpaper',
        paperSize: '',
        machineType: '5 Color Press',
    },
    {
        id: 4,
        type: 'Endpaper',
        component: '1pp',
        qty: '1',
        printingSheets: '10',
        scrap: '70',
        totalSheets: '80',
        colour: '5x0',
        paper: '130gsm Glossy Artpaper',
        paperSize: '',
        machineType: '5 Color Press',
    },
    {
        id: 5,
        type: 'Insert',
        component: '1pp',
        qty: '1',
        printingSheets: '10',
        scrap: '70',
        totalSheets: '80',
        colour: '5x0',
        paper: '130gsm Glossy Artpaper',
        paperSize: '',
        machineType: '5 Color Press',
    },
];