export const OrderJobDataList = [
    {
        Id: 1,
        JobNo: '984800',
        // orderDate: Date.now(),
        // rdd: Date.now(),
        ISBNPartNo: '9780124059351',
        OrderQuantity: '50,120',
        PrintType: 'Offset',
        CurrentActivityStatusCode: 201,
        CaseID: '',
        CaseDetailNo: '',
        ProductVersion: '',
        ParentISBN: '',
        Type: '',
        ComponentType: '',
        JobType: '',
        ProductGroup: '',
        YourReference: '',
        Title: '',
        LnNo: '',
        ExtLnNo: '',
        ExtJobNo: null,
        SellToNo: '',
        BindingType: '',
        TotalExtent: 0,
        Weight: '',
        Spine: '',
        AdditionalUnitPrice: 0,
        AdditionalQty: 0,
        Margin: 0,
        ProductionQuantity: 0,
        EstimatedPrice: 0,
        QuotedPrice: 0,
        SellingPrice: 0,
        SubTotal: 0,
        SamplesRequired: 0,
        BluePrintRequired: 0,
        FGRequired: 0,
        AdvancesRequired: 0,
        CarrierSheet: '',
        IsDeleted: null,
        CurrentActivityId: 0,
        CurrentActivityStatusName: '',
        CreatedByUser: '',
        CreatedBy: '',
        CreatedDateTime: 0,
        CpdatedByUser: '',
        CpdatedBy: '',
        CpdatedDateTime: 0,
        CequestedDeliveryDate: 0,
        CaseDetailAddiotional: []
    },
    // {
    //     id: 2,
    //     jobNo: '984789',
    //     // orderDate: Date.now(),
    //     // rdd: Date.now(),
    //     isbn: '9780124059351',
    //     qty: '50,120',
    //     jobType: 'Offset',
    //     status: 'Shipped'
    // },
    // {
    //     id: 3,
    //     jobNo: '984797',
    //     orderDate: Date.now(),
    //     rdd: Date.now(),
    //     isbn: '9780124059351',
    //     qty: '49,000',
    //     jobType: 'Offset',
    //     status: 'Shipped'
    // },
    // {
    //     id: 4,
    //     jobNo: '984793',
    //     orderDate: Date.now(),
    //     rdd: Date.now(),
    //     isbn: '9780124059351',
    //     qty: '40,500',
    //     jobType: 'Offset',
    //     status: 'Printing'
    // },
    // {
    //     id: 5,
    //     jobNo: '984795',
    //     orderDate: Date.now(),
    //     rdd: Date.now(),
    //     isbn: '9780124059351',
    //     qty: '80,000',
    //     jobType: 'Offset',
    //     status: 'Shipped'
    // },
];