export const PlatemakingDataList = [
    {
        id: 1,
        jobNo: '984801',
        customer: 'Pearson 1',
        isbn: '9712365214we 1',
        press: 'Integrity 1',
        platesToBeReadyBy: Date.now(),
        printingDate: Date.now(),
        qty: '22',
        webcode: 'No',
        status: 'Outstanding',
    },
    {
        id: 2,
        jobNo: '984800',
        customer: 'Pearson',
        isbn: '9712365214we',
        press: 'Integrity',
        platesToBeReadyBy: Date.now(),
        printingDate: Date.now(),
        qty: '22',
        webcode: 'Yes',
        status: 'Completed',
    },
    {
        id: 3,
        jobNo: '984800',
        customer: 'Pearson',
        isbn: '9712365214we',
        press: 'Integrity',
        platesToBeReadyBy: Date.now(),
        printingDate: Date.now(),
        qty: '22',
        webcode: 'Yes',
        status: 'Completed',
    },
    {
        id: 4,
        jobNo: '984800',
        customer: 'Pearson',
        isbn: '9712365214we',
        press: 'Integrity',
        platesToBeReadyBy: Date.now(),
        printingDate: Date.now(),
        qty: '22',
        webcode: 'Yes',
        status: 'Planning',
    },
    {
        id: 5,
        jobNo: '984800',
        customer: 'Pearson',
        isbn: '9712365214we',
        press: 'Integrity',
        platesToBeReadyBy: Date.now(),
        printingDate: Date.now(),
        qty: '22',
        webcode: 'Yes',
        status: 'Planning',
    },
    {
        id: 6,
        jobNo: '984800',
        customer: 'Pearson',
        isbn: '9712365214we',
        press: 'Integrity',
        platesToBeReadyBy: Date.now(),
        printingDate: Date.now(),
        qty: '22',
        webcode: 'Yes',
        status: 'Scheduling',
    },
];
