export const QuotationDataList = [
    {
        id: 1,
        dateCreated: Date.now(),
        caseNo: '000144',
        customer: 'DPS094-MS',
        salesPerson: 'John Doe',
        estNo: 'EST123',
        quoteNo: 'QU000051',
        status: 'Pending Est.',
    },
    {
        id: 2,
        dateCreated: Date.now(),
        caseNo: '000144',
        customer: 'DPS094-MS',
        salesPerson: 'Alina Mil',
        estNo: 'EST123',
        quoteNo: 'QU000051',
        status: 'Est. Compl.',
    },
    {
        id: 3,
        dateCreated: Date.now(),
        caseNo: '000144',
        customer: 'DPS094-MS',
        salesPerson: 'Milenda Cerny',
        estNo: 'EST123',
        quoteNo: 'QU000051',
        status: 'Est. Recommit.',
    },
    {
        id: 4,
        dateCreated: Date.now(),
        caseNo: '000144',
        customer: 'DPS094-MS',
        salesPerson: 'Bill Moro',
        estNo: 'EST123',
        quoteNo: 'QU000051',
        status: 'Quote Sent',
    },
];
